######################################################################
# Automatically generated by qmake (2.01a) ? 5? 24 17:23:35 2016
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += testgui.cpp
